version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vite
    versions:
    - 2.0.0
    - 2.0.0-beta.70
    - 2.1.0
    - 2.1.1
